Trigger merge-[CICD]-Update 5 test files+yml to get args; combine to cicd br

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -32,16 +32,16 @@ test-model:
   tags:
     - testocr
   script:
-    #    - export CUDA_VISIBLE_DEVICES=1
-    - conda activate akaocr
-    - cd akaocr
-    - pip install -r requirements.txt
+    #    - export CUDA_VISIBLE_DEVICES=1 #in case 1st gpu full (2 gpus)
+    - conda activate akaocr #activate existed env; create a new env when use Docker
+    - cd akaocr #cd to source
+    - pip install -r requirements.txt #install for the 1st time only
     - pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio===0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
     - pip install anybadge
     - cd test
     - export exit_code=0 #success by default
     - export result=""
-    - python models_test.py || export exit_code=1
+    - python models_test.py --config_recog_yaml='../data/attention_resnet_base_v1.yaml'  || export exit_code=1
     - echo $exit_code
     - >
       if [ ${exit_code} -ne 0 ]; then
@@ -50,13 +50,17 @@ test-model:
         export result="passed";
       fi
     - echo $result
-    - anybadge --label="test model" --value=${result} --file=test_model.svg passed=green failed=red
-    
+    - anybadge --label="test model" --value=${result} --file=test_model.svg passed=green failed=red #create badge for job
+    - >
+      if [ ${exit_code} -ne 0 ]; then
+        exit 1;
+      fi
   artifacts:
     paths:
-      - akaocr/test/test_model.svg
-    when: always
-  # allow_failure: true
+      - akaocr/test/test_model.svg #artifact, path as cd when the badge was created
+    when: always #upload on both success and fail job
+  allow_failure:
+    exit_codes: 137 #a number !=1 to make the job failed if it actually fail
 
 test-config:
   extends:
@@ -80,11 +84,16 @@ test-config:
       fi
     - echo $result
     - anybadge --label="test config" --value=${result} --file=test_config.svg passed=green failed=red
+    - >
+      if [ ${exit_code} -ne 0 ]; then
+        exit 1;
+      fi
   artifacts:
     paths:
       - akaocr/test/test_config.svg
     when: always
-  # allow_failure: true
+  allow_failure:
+    exit_codes: 137
 
 test-dataloader:
   extends:
@@ -98,7 +107,7 @@ test-dataloader:
     - cd test
     - export exit_code=0 #success by default
     - export result=""
-    - python test_dataloader.py || export exit_code=1
+    - python test_dataloader.py --root_data_recog='/home/bacnv6/nghiann3/data/RECOG/' --root_data_detec='/home/tanhv1/kleentext/akaocr/data/data_detec/train/' || export exit_code=1
     - echo $exit_code
     - >
       if [ ${exit_code} -ne 0 ]; then
@@ -108,11 +117,16 @@ test-dataloader:
       fi
     - echo $result
     - anybadge --label="test dataloader" --value=${result} --file=test_dataloader.svg passed=green failed=red
+    - >
+      if [ ${exit_code} -ne 0 ]; then
+        exit 1;
+      fi
   artifacts:
     paths:
       - akaocr/test/test_dataloader.svg
     when: always
-  # allow_failure: true
+  allow_failure:
+    exit_codes: 137
 
 test-eval:
   extends:
@@ -126,7 +140,7 @@ test-eval:
     - cd test
     - export exit_code=0 #success by default
     - export result=""
-    - python evaluation_test.py || export exit_code=1
+    - python evaluation_test.py --model_detec_path='/home/tanhv1/kleentext/akaocr/data/saved_models_detec/smz_detec/best_accuracy.pth' --data_detec_path='/home/tanhv1/kleentext/akaocr/data/data_detec/train/' --model_recog_path='/home/bacnv6/nghiann3/ocr-old/data/saved_models_recog/test1/best_accuracy.pth' --data_recog_path='/home/bacnv6/nghiann3/data/RECOG/' || export exit_code=1
     - echo $exit_code
     - >
       if [ ${exit_code} -ne 0 ]; then
@@ -145,7 +159,7 @@ test-eval:
       - akaocr/test/test_evaluation.svg
     when: always
   allow_failure:
-    exit_codes: 1
+    exit_codes: 137
 
 test-train-loop:
   extends:
@@ -159,7 +173,7 @@ test-train-loop:
     - cd test
     - export exit_code=0 #success by default
     - export result=""
-    - python train_loop_test.py || export exit_code=1
+    - python train_loop_test.py --root_data_recog='/home/bacnv6/nghiann3/data/RECOG/' --root_data_detec='/home/tanhv1/kleentext/akaocr/data/data_detec/train/' --data_test_path='/home/tanhv1/kleentext/akaocr/data/data_detec/test/ST_Doc_WORD_v2_2/' || export exit_code=1
     - echo $exit_code
     - >
       if [ ${exit_code} -ne 0 ]; then
@@ -169,8 +183,13 @@ test-train-loop:
       fi
     - echo $result
     - anybadge --label="test training loop" --value=${result} --file=test_train_loop.svg passed=green failed=red
+    - >
+      if [ ${exit_code} -ne 0 ]; then
+        exit 1;
+      fi
   artifacts:
     paths:
       - akaocr/test/test_train_loop.svg
     when: always
-  # allow_failure: true
+  allow_failure:
+    exit_codes: 137
