Update 5 test cases to run on docker

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -152,29 +152,34 @@ train-recog-docker:
   allow_failure:
     exit_codes: 137
 
-
-    
-## test stage for merge process
-
-test-model:
+##test in docker
+test-model-docker:
   extends:
     - .requires-trigger-merge-commit-message
   stage: test
   tags:
-    - shell
+    - docker
+  image: $CI_REGISTRY_IMAGE:${DOCKER_TAG}
   script:
+    # - mkdir runner_data_test
+    # - mkdir runner_model_test
     - echo $CI_JOB_STAGE
-    # - conda env create -f jobs/environment.yml -q #config new env to create if not exist, when use docker
-    - conda activate akaocr #activate existed env; create a new env when use Docker
-    - cd akaocr #cd to source
-    - pip install -r requirements.txt #install for the 1st time only
-    - pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio===0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
-    - pip install anybadge
-    - cd test
-    - export exit_code=0 #success by default
+    - cd akaocr/test
+      #success code init
+    - export exit_code=0 
     - export result=""
+      #configured [runner.docker]'s gpus="all" in runner config (config.toml), nano /etc/gitlab-runner/config.toml
+    # - nvidia-smi
+      #mount data from NAS to runner's container; note: configure [runner.docker]'s shm_size big enough
+      #data test
+    # - mount -t cifs -o username=coeteam,password=Qai@2021,dir_mode=0777,file_mode=0777 '\\10.134.181.67\qai_storage\Synthtext_output\DATA_PROJECT\' /builds/cuongvt/ocr-components/runner_data_test/
+      #saved model
+    # - mount -t cifs -o username=coeteam,password=Qai@2021,dir_mode=0777,file_mode=0777 '\\10.134.181.67\QAI_STORAGE\Trained_models\' /builds/cuongvt/ocr-components/runner_model_test/
     - python models_test.py --config_recog "../data/attention_resnet_base_v1.yaml"  || export exit_code=1
-    - echo $exit_code
+      #unmount data from NAS
+    # - umount /builds/cuongvt/ocr-components/runner_data_test/
+    # - umount /builds/cuongvt/ocr-components/runner_model_test/
+      #base on exit_code to create badge result
     - >
       if [ ${exit_code} -ne 0 ]; then
         export result="failed";
@@ -182,33 +187,45 @@ test-model:
         export result="passed";
       fi
     - echo $result
-    - anybadge --label="test model" --value=${result} --file=badge_test_model.svg passed=green failed=red #create badge for job
+    - anybadge --label="test model" --value=${result} --file=/builds/cuongvt/ocr-components/akaocr/tools/badge_test_model.svg -o passed=green failed=red
     - >
       if [ ${exit_code} -ne 0 ]; then
         exit 1;
       fi
   artifacts:
     paths:
-      - akaocr/test/badge_test_model.svg #artifact, path as cd when the badge was created
-    when: always #upload on both success and fail job
+      - akaocr/test/badge_test_model.svg
+    when: always
   allow_failure:
-    exit_codes: 137 #a number !=1 to make the job failed if it actually fail
+    exit_codes: 137
 
-test-config:
+test-config-docker:
   extends:
     - .requires-trigger-merge-commit-message
   stage: test
   tags:
-    - shell
+    - docker
+  image: $CI_REGISTRY_IMAGE:${DOCKER_TAG}
   script:
+    # - mkdir runner_data_test
+    # - mkdir runner_model_test
     - echo $CI_JOB_STAGE
-    - conda activate akaocr
-    - cd akaocr
-    - cd test
-    - export exit_code=0 #success by default
+    - cd akaocr/test
+      #success code init
+    - export exit_code=0 
     - export result=""
+      #configured [runner.docker]'s gpus="all" in runner config (config.toml), nano /etc/gitlab-runner/config.toml
+    # - nvidia-smi
+      #mount data from NAS to runner's container; note: configure [runner.docker]'s shm_size big enough
+      #data test
+    # - mount -t cifs -o username=coeteam,password=Qai@2021,dir_mode=0777,file_mode=0777 '\\10.134.181.67\qai_storage\Synthtext_output\DATA_PROJECT\' /builds/cuongvt/ocr-components/runner_data_test/
+      #saved model
+    # - mount -t cifs -o username=coeteam,password=Qai@2021,dir_mode=0777,file_mode=0777 '\\10.134.181.67\QAI_STORAGE\Trained_models\' /builds/cuongvt/ocr-components/runner_model_test/
     - python config_test.py || export exit_code=1
-    - echo $exit_code
+      #unmount data from NAS
+    # - umount /builds/cuongvt/ocr-components/runner_data_test/
+    # - umount /builds/cuongvt/ocr-components/runner_model_test/
+      #base on exit_code to create badge result
     - >
       if [ ${exit_code} -ne 0 ]; then
         export result="failed";
@@ -216,7 +233,7 @@ test-config:
         export result="passed";
       fi
     - echo $result
-    - anybadge --label="test config" --value=${result} --file=badge_test_config.svg passed=green failed=red
+    - anybadge --label="test config" --value=${result} --file=/builds/cuongvt/ocr-components/akaocr/tools/badge_test_config.svg -o passed=green failed=red
     - >
       if [ ${exit_code} -ne 0 ]; then
         exit 1;
@@ -228,21 +245,33 @@ test-config:
   allow_failure:
     exit_codes: 137
 
-test-dataloader:
+test-dataloader-docker:
   extends:
     - .requires-trigger-merge-commit-message
   stage: test
   tags:
-    - shell
+    - docker
+  image: $CI_REGISTRY_IMAGE:${DOCKER_TAG}
   script:
+    - mkdir runner_data_test
+    - mkdir runner_model_test
     - echo $CI_JOB_STAGE
-    - conda activate akaocr
-    - cd akaocr
-    - cd test
-    - export exit_code=0 #success by default
+    - cd akaocr/test
+      #success code init
+    - export exit_code=0 
     - export result=""
-    - python test_dataloader.py --data_recog $DATA_RECOG --data_detec $DATA_DETEC || export exit_code=1
-    - echo $exit_code
+      #configured [runner.docker]'s gpus="all" in runner config (config.toml), nano /etc/gitlab-runner/config.toml
+    # - nvidia-smi
+      #mount data from NAS to runner's container; note: configure [runner.docker]'s shm_size big enough
+      #data test
+    - mount -t cifs -o username=coeteam,password=Qai@2021,dir_mode=0777,file_mode=0777 '\\10.134.181.67\qai_storage\Synthtext_output\DATA_PROJECT\' /builds/cuongvt/ocr-components/runner_data_test/
+      #saved model
+    - mount -t cifs -o username=coeteam,password=Qai@2021,dir_mode=0777,file_mode=0777 '\\10.134.181.67\QAI_STORAGE\Trained_models\' /builds/cuongvt/ocr-components/runner_model_test/
+    - python test_dataloader.py --data_recog $DATA_RECOG_DOCKER --data_detec $DATA_DETEC_DOCKER || export exit_code=1
+      #unmount data from NAS
+    - umount /builds/cuongvt/ocr-components/runner_data_test/
+    - umount /builds/cuongvt/ocr-components/runner_model_test/
+      #base on exit_code to create badge result
     - >
       if [ ${exit_code} -ne 0 ]; then
         export result="failed";
@@ -250,7 +279,7 @@ test-dataloader:
         export result="passed";
       fi
     - echo $result
-    - anybadge --label="test dataloader" --value=${result} --file=badge_test_dataloader.svg passed=green failed=red
+    - anybadge --label="test dataloader" --value=${result} --file=/builds/cuongvt/ocr-components/akaocr/tools/badge_test_dataloader.svg -o passed=green failed=red
     - >
       if [ ${exit_code} -ne 0 ]; then
         exit 1;
@@ -261,22 +290,34 @@ test-dataloader:
     when: always
   allow_failure:
     exit_codes: 137
-
-test-eval:
+    
+test-eval-docker:
   extends:
     - .requires-trigger-merge-commit-message
   stage: test
   tags:
-    - shell
+    - docker
+  image: $CI_REGISTRY_IMAGE:${DOCKER_TAG}
   script:
+    - mkdir runner_data_test
+    - mkdir runner_model_test
     - echo $CI_JOB_STAGE
-    - conda activate akaocr
-    - cd akaocr
-    - cd test
-    - export exit_code=0 #success by default
+    - cd akaocr/test
+      #success code init
+    - export exit_code=0 
     - export result=""
-    - python evaluation_test.py --w_detec $W_DETEC --data_test_detec $DATA_TEST_DETEC --w_recog $W_RECOG --data_recog $DATA_RECOG || export exit_code=1
-    - echo $exit_code
+      #configured [runner.docker]'s gpus="all" in runner config (config.toml), nano /etc/gitlab-runner/config.toml
+    # - nvidia-smi
+      #mount data from NAS to runner's container; note: configure [runner.docker]'s shm_size big enough
+      #data test
+    - mount -t cifs -o username=coeteam,password=Qai@2021,dir_mode=0777,file_mode=0777 '\\10.134.181.67\qai_storage\Synthtext_output\DATA_PROJECT\' /builds/cuongvt/ocr-components/runner_data_test/
+      #saved model
+    - mount -t cifs -o username=coeteam,password=Qai@2021,dir_mode=0777,file_mode=0777 '\\10.134.181.67\QAI_STORAGE\Trained_models\' /builds/cuongvt/ocr-components/runner_model_test/
+    - python evaluation_test.py --w_detec $W_DETEC_DOCKER --data_test_detec $DATA_TEST_DETEC_DOCKER --w_recog $W_RECOG_DOCKER --data_recog $DATA_RECOG_DOCKER || export exit_code=1
+      #unmount data from NAS
+    - umount /builds/cuongvt/ocr-components/runner_data_test/
+    - umount /builds/cuongvt/ocr-components/runner_model_test/
+      #base on exit_code to create badge result
     - >
       if [ ${exit_code} -ne 0 ]; then
         export result="failed";
@@ -284,7 +325,7 @@ test-eval:
         export result="passed";
       fi
     - echo $result
-    - anybadge --label="test evaluation" --value=${result} --file=badge_test_evaluation.svg passed=green failed=red
+    - anybadge --label="test evaluation" --value=${result} --file=/builds/cuongvt/ocr-components/akaocr/tools/badge_test_evaluation.svg -o passed=green failed=red
     - >
       if [ ${exit_code} -ne 0 ]; then
         exit 1;
@@ -296,22 +337,33 @@ test-eval:
   allow_failure:
     exit_codes: 137
 
-test-train-loop:
+test-eval-docker:
   extends:
     - .requires-trigger-merge-commit-message
   stage: test
   tags:
-    - shell
+    - docker
+  image: $CI_REGISTRY_IMAGE:${DOCKER_TAG}
   script:
+    - mkdir runner_data_test
+    - mkdir runner_model_test
     - echo $CI_JOB_STAGE
-    - conda activate akaocr
-    - cd akaocr
-    - cd test
-    - export exit_code=0 #success by default
+    - cd akaocr/test
+      #success code init
+    - export exit_code=0 
     - export result=""
+      #configured [runner.docker]'s gpus="all" in runner config (config.toml), nano /etc/gitlab-runner/config.toml
     - nvidia-smi
-    - python train_loop_test.py --test_train_type detec --config="../data/heatmap_1fpn_v1_ci_test.yaml" --data_detec $DATA_DETEC --data_test_detec $DATA_TEST_DETEC && python train_loop_test.py --test_train_type recog --config="../data/attention_resnet_base_v1_ci_test.yaml" --data_recog $DATA_RECOG || export exit_code=1
-    - echo $exit_code
+      #mount data from NAS to runner's container; note: configure [runner.docker]'s shm_size big enough
+      #data test
+    - mount -t cifs -o username=coeteam,password=Qai@2021,dir_mode=0777,file_mode=0777 '\\10.134.181.67\qai_storage\Synthtext_output\DATA_PROJECT\' /builds/cuongvt/ocr-components/runner_data_test/
+      #saved model
+    - mount -t cifs -o username=coeteam,password=Qai@2021,dir_mode=0777,file_mode=0777 '\\10.134.181.67\QAI_STORAGE\Trained_models\' /builds/cuongvt/ocr-components/runner_model_test/
+    - python train_loop_test.py --test_train_type detec --config="../data/heatmap_1fpn_v1_ci_test.yaml" --data_detec $DATA_DETEC_DOCKER --data_test_detec $DATA_TEST_DETEC_DOCKER && python train_loop_test.py --test_train_type recog --config="../data/attention_resnet_base_v1_ci_test.yaml" --data_recog $DATA_RECOG_DOCKER || export exit_code=1
+      #unmount data from NAS
+    - umount /builds/cuongvt/ocr-components/runner_data_test/
+    - umount /builds/cuongvt/ocr-components/runner_model_test/
+      #base on exit_code to create badge result
     - >
       if [ ${exit_code} -ne 0 ]; then
         export result="failed";
@@ -319,7 +371,7 @@ test-train-loop:
         export result="passed";
       fi
     - echo $result
-    - anybadge --label="test training loop" --value=${result} --file=badge_test_train_loop.svg passed=green failed=red
+    - anybadge --label="test training loop" --value=${result} --file=/builds/cuongvt/ocr-components/akaocr/tools/badge_test_train_loop.svg -o passed=green failed=red
     - >
       if [ ${exit_code} -ne 0 ]; then
         exit 1;
@@ -330,6 +382,183 @@ test-train-loop:
     when: always
   allow_failure:
     exit_codes: 137
+
+## test stage for merge process
+
+# test-model:
+#   extends:
+#     - .requires-trigger-merge-commit-message
+#   stage: test
+#   tags:
+#     - shell
+#   script:
+#     - echo $CI_JOB_STAGE
+#     # - conda env create -f jobs/environment.yml -q #config new env to create if not exist, when use docker
+#     - conda activate akaocr #activate existed env; create a new env when use Docker
+#     - cd akaocr #cd to source
+#     - pip install -r requirements.txt #install for the 1st time only
+#     - pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio===0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
+#     - pip install anybadge
+#     - cd test
+#     - export exit_code=0 #success by default
+#     - export result=""
+#     - python models_test.py --config_recog "../data/attention_resnet_base_v1.yaml"  || export exit_code=1
+#     - echo $exit_code
+#     - >
+#       if [ ${exit_code} -ne 0 ]; then
+#         export result="failed";
+#       else
+#         export result="passed";
+#       fi
+#     - echo $result
+#     - anybadge --label="test model" --value=${result} --file=badge_test_model.svg passed=green failed=red #create badge for job
+#     - >
+#       if [ ${exit_code} -ne 0 ]; then
+#         exit 1;
+#       fi
+#   artifacts:
+#     paths:
+#       - akaocr/test/badge_test_model.svg #artifact, path as cd when the badge was created
+#     when: always #upload on both success and fail job
+#   allow_failure:
+#     exit_codes: 137 #a number !=1 to make the job failed if it actually fail
+
+# test-config:
+#   extends:
+#     - .requires-trigger-merge-commit-message
+#   stage: test
+#   tags:
+#     - shell
+#   script:
+#     - echo $CI_JOB_STAGE
+#     - conda activate akaocr
+#     - cd akaocr
+#     - cd test
+#     - export exit_code=0 #success by default
+#     - export result=""
+#     - python config_test.py || export exit_code=1
+#     - echo $exit_code
+#     - >
+#       if [ ${exit_code} -ne 0 ]; then
+#         export result="failed";
+#       else
+#         export result="passed";
+#       fi
+#     - echo $result
+#     - anybadge --label="test config" --value=${result} --file=badge_test_config.svg passed=green failed=red
+#     - >
+#       if [ ${exit_code} -ne 0 ]; then
+#         exit 1;
+#       fi
+#   artifacts:
+#     paths:
+#       - akaocr/test/badge_test_config.svg
+#     when: always
+#   allow_failure:
+#     exit_codes: 137
+
+# test-dataloader:
+#   extends:
+#     - .requires-trigger-merge-commit-message
+#   stage: test
+#   tags:
+#     - shell
+#   script:
+#     - echo $CI_JOB_STAGE
+#     - conda activate akaocr
+#     - cd akaocr
+#     - cd test
+#     - export exit_code=0 #success by default
+#     - export result=""
+#     - python test_dataloader.py --data_recog $DATA_RECOG --data_detec $DATA_DETEC || export exit_code=1
+#     - echo $exit_code
+#     - >
+#       if [ ${exit_code} -ne 0 ]; then
+#         export result="failed";
+#       else
+#         export result="passed";
+#       fi
+#     - echo $result
+#     - anybadge --label="test dataloader" --value=${result} --file=badge_test_dataloader.svg passed=green failed=red
+#     - >
+#       if [ ${exit_code} -ne 0 ]; then
+#         exit 1;
+#       fi
+#   artifacts:
+#     paths:
+#       - akaocr/test/badge_test_dataloader.svg
+#     when: always
+#   allow_failure:
+#     exit_codes: 137
+
+# test-eval:
+#   extends:
+#     - .requires-trigger-merge-commit-message
+#   stage: test
+#   tags:
+#     - shell
+#   script:
+#     - echo $CI_JOB_STAGE
+#     - conda activate akaocr
+#     - cd akaocr
+#     - cd test
+#     - export exit_code=0 #success by default
+#     - export result=""
+#     - python evaluation_test.py --w_detec $W_DETEC --data_test_detec $DATA_TEST_DETEC --w_recog $W_RECOG --data_recog $DATA_RECOG || export exit_code=1
+#     - echo $exit_code
+#     - >
+#       if [ ${exit_code} -ne 0 ]; then
+#         export result="failed";
+#       else
+#         export result="passed";
+#       fi
+#     - echo $result
+#     - anybadge --label="test evaluation" --value=${result} --file=badge_test_evaluation.svg passed=green failed=red
+#     - >
+#       if [ ${exit_code} -ne 0 ]; then
+#         exit 1;
+#       fi
+#   artifacts:
+#     paths:
+#       - akaocr/test/badge_test_evaluation.svg
+#     when: always
+#   allow_failure:
+#     exit_codes: 137
+
+# test-train-loop:
+#   extends:
+#     - .requires-trigger-merge-commit-message
+#   stage: test
+#   tags:
+#     - shell
+#   script:
+#     - echo $CI_JOB_STAGE
+#     - conda activate akaocr
+#     - cd akaocr
+#     - cd test
+#     - export exit_code=0 #success by default
+#     - export result=""
+#     - nvidia-smi
+#     - python train_loop_test.py --test_train_type detec --config="../data/heatmap_1fpn_v1_ci_test.yaml" --data_detec $DATA_DETEC --data_test_detec $DATA_TEST_DETEC && python train_loop_test.py --test_train_type recog --config="../data/attention_resnet_base_v1_ci_test.yaml" --data_recog $DATA_RECOG || export exit_code=1
+#     - echo $exit_code
+#     - >
+#       if [ ${exit_code} -ne 0 ]; then
+#         export result="failed";
+#       else
+#         export result="passed";
+#       fi
+#     - echo $result
+#     - anybadge --label="test training loop" --value=${result} --file=badge_test_train_loop.svg passed=green failed=red
+#     - >
+#       if [ ${exit_code} -ne 0 ]; then
+#         exit 1;
+#       fi
+#   artifacts:
+#     paths:
+#       - akaocr/test/badge_test_train_loop.svg
+#     when: always
+#   allow_failure:
+#     exit_codes: 137
 
 
 
